descriptor-schema-version: "2.0"
info:
  author-link: "http://www.cisco.com/"
  author-name: "Davi Garcia (davigar@cisco.com)"
  description: "Demo IOx App talking with sensor through RS232 serial interface."
  name: "serial_mqtt_app"
  version: "0.2"

app:
  type: paas
  resources:
    profile: c1.small
    devices:
      -
        device-id: serial_mqtt_app
        label: serial_mqtt_app
        type: serial
        usage: "Sensor Interface"

    network:
     -
       interface-name: eth0
       ports:
         tcp:
           - 9000
    recommendations:
      -
        description: "This is a sample of recomendation."
        label: "50 Sensors"
        profile: c1.small

  startup:
    runtime: python
    runtime-version: 2.7.3
    target: main.py
